// <auto-generated />
using System;
using MOHRecognition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MOHRecognition.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MOHRecognition.DTOs.AdvisorDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Advisors", (string)null);
                });

            modelBuilder.Entity("MOHRecognition.DTOs.EmployeeDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("MOHRecognition.DTOs.MeetingDecisionDto", b =>
                {
                    b.Property<int>("MeetingId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MeetingId", "RequestId");

                    b.HasIndex("Decision");

                    b.HasIndex("MeetingId");

                    b.HasIndex("RequestId");

                    b.ToTable("MeetingDecisions", (string)null);
                });

            modelBuilder.Entity("MOHRecognition.DTOs.MeetingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationOrPlatform")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeetingTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RequestIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RequestIdsJson");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingDate");

                    b.HasIndex("SessionNumber");

                    b.HasIndex("Status");

                    b.ToTable("Meetings", (string)null);
                });

            modelBuilder.Entity("MOHRecognition.Data.MeetingAttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("MeetingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MeetingId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("MeetingAttendances", (string)null);
                });

            modelBuilder.Entity("MOHRecognition.Services.RecognitionRequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AcademicInfoJson");

                    b.Property<string>("AccreditationBodies")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AccreditationBodiesJson");

                    b.Property<string>("AccreditationNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccreditationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdditionalFiles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AdditionalFilesJson");

                    b.Property<string>("AdditionalNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdmissionRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AdmissionRequirementsJson");

                    b.Property<string>("AdmissionStudyDurationReview")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AdmissionStudyDurationReviewJson");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssignedMember")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AttachmentsJson");

                    b.Property<string>("BasicInfoAssessmentDecision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BasicInfoAssessmentReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Faculties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FacultiesJson");

                    b.Property<string>("FacultiesAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacultiesAssessmentNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GlobalRankings")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("GlobalRankingsJson");

                    b.Property<string>("HospitalEnvironmentAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HospitalEnvironmentAssessmentNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hospitals")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HospitalsJson");

                    b.Property<string>("HospitalsAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HospitalsAssessmentNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Infrastructure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InfrastructureJson");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<string>("Laboratories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LaboratoriesJson");

                    b.Property<string>("LaboratoriesFacilitiesAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LaboratoriesFacilitiesAssessmentNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Library")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LibraryJson");

                    b.Property<string>("LibraryAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LibraryAssessmentNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ManualDataFilled")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicineDentistry")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MedicineDentistryJson");

                    b.Property<string>("Pictures")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PicturesJson");

                    b.Property<string>("ProgramHours")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProgramHoursJson");

                    b.Property<string>("Programs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProgramsJson");

                    b.Property<string>("PublicInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PublicInfoJson");

                    b.Property<string>("RecognitionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecognitionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StudyDuration")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("StudyDurationJson");

                    b.Property<string>("StudyPlanComplianceRows")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("StudyPlanComplianceJson");

                    b.Property<string>("SubmitApplication")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SubmitApplicationJson");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubmittedToAdminAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedToAdminBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniRecAcc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UniRecAccJson");

                    b.Property<string>("UniversityEmail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("WorkPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationType");

                    b.HasIndex("AssignedMember");

                    b.HasIndex("IsManual");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("Year");

                    b.ToTable("RecognitionRequests", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
